### ISSUE TITLE
Backgroundarr superfluous volumes required for container

### ISSUE THREAD

**Issue by ianweatherburn** [anthonysnyder/backgroundarr#1]
Trying out your _backgroundarr_ container (thank you by the way).

In order to get the container past the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/<name>'
```

it was necessary to create **ALL** of these redundant volumes in the container to get the front-end working and bypass the error.

```
/home/iwadmin/Docker/AppData/kometa/assets/metadata/movies | /movies
/home/iwadmin/Docker/AppData/kometa/assets/metadata/shows | /tv
/home/iwadmin/Docker/AppData/kometa/assets/metadata/shows | /kids-tv2
/home/iwadmin/Docker/AppData/kometa/assets/metadata/movies | /kids-movies2
/home/iwadmin/Docker/AppData/kometa/assets/metadata/shows | /tv2
/home/iwadmin/Docker/AppData/kometa/assets/metadata/shows | /shows
/home/iwadmin/Docker/AppData/kometa/assets/metadata/movies | /kids-movies
/home/iwadmin/Docker/AppData/kometa/assets/metadata/movies | /movies2
/home/iwadmin/Docker/AppData/kometa/assets/metadata/shows | /kids-tv

```

Would be great if just `/movies` and `/tv` (or `/shows`) were mandatory (and the documentation aligned).
Thank you.

**Comment by anthonysnyder** [comment]
Thank you for flagging. I know what caused this. I can fix it easily. -TSent from my iPhoneOn Jan 25, 2025, at 11:19 PM, Ian Weatherburn ***@***.***> wrote:﻿
Trying out your backgroundarr container (thank you by the way).
In order to get the container past the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/<name>'

it was necessary to create ALL of these redundant volumes in the container to get the front-end working and bypass the error.
/home/iwadmin/Docker/AppData/kometa/assets/metadata/movies | /movies
/home/iwadmin/Docker/AppData/kometa/assets/metadata/shows | /tv
/home/iwadmin/Docker/AppData/kometa/assets/metadata/shows | /kids-tv2
/home/iwadmin/Docker/AppData/kometa/assets/metadata/movies | /kids-movies2
/home/iwadmin/Docker/AppData/kometa/assets/metadata/shows | /tv2
/home/iwadmin/Docker/AppData/kometa/assets/metadata/shows | /shows
/home/iwadmin/Docker/AppData/kometa/assets/metadata/movies | /kids-movies
/home/iwadmin/Docker/AppData/kometa/assets/metadata/movies | /movies2
/home/iwadmin/Docker/AppData/kometa/assets/metadata/shows | /kids-tv


Would be great if just /movies and /tv (or /shows) were mandatory (and the documentation aligned).
Thank you.

**Comment by anthonysnyder** [comment]
```
    volumes:
      - /path/to/your/movies:/movies
      - /path/to/your/tv:/tv
``` 

Fixed the Docker Compose file. Forgot to fix the Volume Paths with generic ones and not the ones specific to my setup.

**Comment by ianweatherburn** [comment]
Apologies, has the latest container been pushed as I am still receiving these errors.

```
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.2:5000
Press CTRL+C to quit
[2025-01-28 06:08:59,573] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 189, in index
    movies, total_movies = get_backdrop_thumbnails(movie_folders)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 134, in get_backdrop_thumbnails
    for media_dir in sorted(os.listdir(base_folder)):
                            ^^^^^^^^^^^^^^^^^^^^^^^
**FileNotFoundError: [Errno 2] No such file or directory: '/movies2'**
192.168.0.154 - - [28/Jan/2025 06:08:59] "GET / HTTP/1.1" 500 -
[2025-01-28 06:09:12,116] ERROR in app: Exception on /tv [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 197, in tv_shows
    tv_shows, total_tv_shows = get_backdrop_thumbnails(tv_folders)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 134, in get_backdrop_thumbnails
    for media_dir in sorted(os.listdir(base_folder)):
                            ^^^^^^^^^^^^^^^^^^^^^^^
**FileNotFoundError: [Errno 2] No such file or directory: '/tv2'**
192.168.0.154 - - [28/Jan/2025 06:09:12] "GET /tv HTTP/1.1" 500 -
```
