### ISSUE TITLE
TMDB searches for folders named with Plex ID not working

### ISSUE THREAD

**Issue by ianweatherburn** [anthonysnyder/backgroundarr#6]
The TMDB lookup is still not working for TV folders only with the {tmdb-XXXX} in them.
Movie lookups are working correctly.

The folders are named with a hyphen after tmdb, ie. {tmdb-XXXX}
In the logs, it appears as though you are looking for {tmdbXXXX} for TV only. 
Movies I can see in the logs {tmdb-XXXX}

**Comment by anthonysnyder** [comment]
Oh no, let me fix that.

**Comment by anthonysnyder** [comment]
I think I resolved this, I just updated the app.route for tv to strip out that data. If you could pull a fresh copy of the repo and try again I would appreciate it

**Comment by ianweatherburn** [comment]
Unfortunately you have introduced another bug in the Python code.

IndentationError: unindent does not match any outer indentation level

  File "/app/app.py", line 206

    return render_template('index.html', movies=movies, total_movies=total_movies, content_type="movie")

**Comment by anthonysnyder** [comment]
>.<

Damnit. I’ll poke at it tomorrow

**Comment by anthonysnyder** [comment]
@ianweatherburn Can you try pulling again, I pushed an update to the repo for another issue and think I (unintentionally) fixed this one at the same time

**Comment by ianweatherburn** [comment]
Are you not able to test this yourself before pushing a release? It is still not working.

Looking for this TV Release "The 100" which is in this folder:
"The 100 (2014) {tmdb-48866}"

produces this output in the log:
31/Jan/2025 10:50:15] "GET /search_tv?query=the%20100%20%20**tmdb48866** HTTP/1.1" 200 -
which returns no results from TMDB.

You can see the search is for "the%20100%20%20tmdb48866" which fails.
You need to add a hyphen after tmdb (tmdb-48866) as that is the correct naming convention (or just use the folder name as passed?)

You have done this movies which is working, why can you not do the same for TV?
i.e. a movie search for:
"The 100 Year-Old Man Who Climbed Out the Window and Disappeared (2013) {tmdb-145247}"

the log shows:
"GET /search_movie?query=The%20100%20Year-Old%20Man%20Who%20Climbed%20Out%20the%20Window%20and%20Disappeared%20(2013)%20{tmdb-145247}&folder_name=The%20100%20Year-Old%20Man%20Who%20Climbed%20Out%20the%20Window%20and%20Disappeared%20(2013)%2**0{tmdb-145247}** HTTP/1.1" 200 -

The same issue occurs with titles that have special characters as you are stripping them, such as the TV show:
"3% (2016) {tmdb-68467}" results in:
Search Results for "3 tmdb68467" - 0 results found

**Comment by anthonysnyder** [comment]
@ianweatherburn I am doing the best I can and yes I am testing things before pushing. It never occurred to me that the changes I made would not apply to the TV folders as well.

**Comment by anthonysnyder** [comment]
The latest branch worked for me: 

192.168.64.1 - - [31/Jan/2025 23:48:40] "GET /search_tv?query=Ahsoka%20{tmdb-114461}&folder_name=Ahsoka%20{tmdb-114461} HTTP/1.1" 200 -
192.168.64.1 - - [31/Jan/2025 23:48:44] "GET /select_tv/114461?folder_name=Ahsoka+{tmdb-114461} HTTP/1.1" 200 -

![Image](https://github.com/user-attachments/assets/95114381-878e-4059-8b47-8b40e6f20e7e)

**Comment by ianweatherburn** [comment]
HI @anthonysnyder , thank you. I can confirm it is working now. 👍
